### ISSUE TITLE
Unsupported Image Format

### ISSUE THREAD

**Issue by dare3219** [ros-visualization/rqt_bag#13]
I am trying to view a set of images from my BAG files however I am seeing the following in the console:

_Can't convert image: Unsupported image format: yuv422_

Is there a plugin available to handle this format?

**Comment by dirk-thomas** [comment]
Please raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
