### ISSUE TITLE
ImportError: No module named qt_gui.plugin

### ISSUE THREAD

**Issue by k123jack** [ros-visualization/rqt_bag#47]
When trying to visualize a bag file using rqt_bag, it showed this error : 

rqt_bag /disk/XXX.bag 

Traceback (most recent call last):
  File "/home/user/roslib/devel/bin/rqt_bag", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/kuser/roslib/src/rqt_bag/rqt_bag/scripts/rqt_bag", line 5, in <module>
    from rqt_bag.bag import Bag
  File "/home/user/roslib/src/rqt_bag/rqt_bag/src/rqt_bag/bag.py", line 37, in <module>
    from qt_gui.plugin import Plugin
ImportError: No module named qt_gui.plugin

Ubuntu : 18.04
ROS : melodic
packages were built through catkin build command.

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
